import 'package:fluttermyappp/conts/conts.dart';

class AppStrings {
  static String appname = "Mediapp",
      bestEmpapp = "Best Employee \n Appointment App",
      welcomeBack = "Welcome Back!",
      weAreExcited = "We're excited to have you back!",
      signupNow = "Sign up now and start exploring all that our app has to offer.",
      email = "Email",
      emailHint = "Enter your email...",
      password = "Password",
      passwordHint = "Enter your password here...",
      fullname = "Full name",
      fullnameHint = "Enter your name here...",
      confirmPassword = "Confirm Password",
      forgetPassword = "Forget Password?",
      login = "Login",
      category = "Category",
      employee = "Employee Login",
      settings = "Settings",
      signup = "Signup",
      search = "Search employee",
      welcome = "Welcome",
      alreadyHaveAccount = "Account have an account?",
      dontHaveAccount = "Don't have an account?",
      haircut = "Haircut",
      hairstyles = "Hairstyles",
      manicure = "Manicure",
      pedicure = "Pedicure",
      makeup = "Makeup",
      faceCleaning = "Face cleaning",
      changePassword = "Change Password",
      termsConditions = "Terms & Conditions",
      signout = "Signout";
}
